name: Codecov

on:
  push:
    branches: [main]

jobs:
  run:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install '.[dev]'
    - name: Generate coverage report
      run: |
        pytest --disable-warnings --cov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.2.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: NREL/infrasys
        # flags: smart-tests
        # name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true
