name: Main - CI

on:
  schedule:
  - cron: "0 0 * * 1-5"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ".[dev]"
    - name: Run pytest
      run: |
        python -m pytest -v --disable-warnings tests
  mypy:
    runs-on: ubuntu-latest
    name: "mypy"
    steps:
      - uses: davidslusser/actions_python_mypy@v1.0.0
        with:
          src: "src"
          options: "--ignore-missing-imports"
  ruff:
    runs-on: ubuntu-latest
    name: "ruff"
    steps:
      - uses: davidslusser/actions_python_ruff@v1.0.0
        with:
          src: "src"
          pip_install_command: "pip install -e .[dev]"
          python_version: "3.11"
